# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Placeholder wedding site
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This will be something awesome soon, I promise! Just hit a few bumps on the way to finishing the site.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.kpwedding.uk" # the base hostname & protocol for your site
twitter_username: 
github_username:  

# Build settings
markdown: kramdown
